<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\WindowMonitorService.cs" />
    <Compile Remove="Services\WinEventSource.cs" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="i18n\Strings.de-DE.resx" />
    <AdditionalFiles Include="i18n\Strings.resx" />
    <AdditionalFiles Include="i18n\Strings.zh-CN.resx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AsyncNavigation" />
    <PackageReference Include="Irihi.Lingua" />
    <PackageReference Include="LibVLCSharp" />
    <PackageReference Include="Microsoft.Windows.CsWin32">
      <PrivateAssets>all</PrivateAssets>
      <!--<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>-->
    </PackageReference>
    <PackageReference Include="ReactiveUI" />
    <PackageReference Include="ReactiveUI.SourceGenerators">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="VideoLAN.LibVLC.Windows" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Peek.Ipc\Peek.Ipc.csproj" />
  </ItemGroup>

</Project>
